#!/bin/sh

# Doc directory
doc_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
pushd $doc_dir

mkdir -p roboptim-core

echo "Downloading getting-started.html"
rm -f roboptim-core/getting-started.html
wget https://raw.githubusercontent.com/roboptim/roboptim-core/master/doc/getting-started.html -O roboptim-core/getting-started.html

echo "Downloading operators-decorators.html"
rm -f roboptim-core/operators-decorators.html
wget https://raw.githubusercontent.com/roboptim/roboptim-core/master/doc/operators-decorators.html -O roboptim-core/operators-decorators.html

popd
